[programs.localnet]
gem_bank = "7KRu52tpJ4hb9qdk4FsBMrWaZxkWt49o6kbW7QMrutc8"
gem_farm = "38yr6ZVQecngTXbad8pj4nbbGdudDHfgfpD6xQJAJG1c"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "wallets/base/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"